### ISSUE TITLE
Deprecation warning on `dispatch`

### ISSUE THREAD

**Issue by AlfioRusso** [BendingSpoons/tempura-swift#107]
[These deprecation warnings](https://github.com/BendingSpoons/tempura-swift/blob/117d339eb69c7823f79cfa4773681f63e843e6f7/Tempura/Navigation/NavigationActions.swift#L166) cannot be easily avoided, because they are more specific and picked by default.
Please remove the extension in the next major release.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199108774605801/1199908445927410) by [Unito](https://www.unito.io/learn-more)

**Comment by LorDisturbia** [comment]
Removed in #115
