### ISSUE TITLE
XCode13 - Failed to set device orientation: Not authorized for performing UI testing actions.

### ISSUE THREAD

**Issue by carlomartinucci** [BendingSpoons/tempura-swift#128]
# TempuraTesting, XCode 13
With XCode 13, `uiTest` fails (in `ViewTestCase where Self: XCTestCase`) when calling `XCUIDevice.shared.orientation = context.orientation` with error `Failed to set device orientation: Not authorized for performing UI testing actions.`.

Sadly, I have no idea how to address this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199108774605801/1201050564831943) by [Unito](https://www.unito.io)

**Comment by loghina** [comment]
Reopening since the device orientation needs to be changed also for ViewTestCase and UIViewControllerTestCase.
