### ISSUE TITLE
Improve StringStyle.fromSketchValues helper

### ISSUE THREAD

**Issue by frankdilo** [BendingSpoons/tempura-swift#15]
While developing TorVPN I was styling a button and wondering why the opacity value I was setting with the color was being ignored:

```swift
StringStyle.fromSketchValues(
      family: .systemFont,
      weight: .semibold,
      size: 14,
      color: UIColor(white: 1.0, alpha: 0.4),
      characterSpacing: 0.57,
      lineSpacing: 16
)
```

It took me a while to realise that this method also takes an `opacity` parameter (defaulting to 1.0) that overrides whatever the opacity of the color I provided.

**Comment by smaramba** [comment]
Closing as we removed helpers from Tempura.
