### ISSUE TITLE
Interface Builder

### ISSUE THREAD

**Issue by matthmart** [BendingSpoons/tempura-swift#45]
Is it possible to initialize view controllers & views using Interface Builder?

**Comment by smaramba** [comment]
One way I can think of is to wrap your `Store` object inside a singleton class, like:
```
class AppStore {
  static let shared: Store<AppState> = Store<AppState>(middleware: [], dependencies: DependenciesContainer.self)
}
```
where AppState is your app state, for instance:
```

**Comment by matthmart** [comment]
Ok, I understand. So we will try to migrate to code for UI, to able to use your great library :)
Thank you for your work!

**Comment by smaramba** [comment]
let me know if you face any issue, or need any clarification

**Comment by xinhuang327** [comment]
I found a simple workaround by overriding loadView of `ViewControllerWithLocalState`,
 just name xib's filename with the same as the view type's name.
 
`class IBViewControllerWithLocalState<V: ViewControllerModellableView & UIView>: ViewControllerWithLocalState<V> where V.VM: ViewModelWithLocalState {
	
	override func loadView() {
		let viewTypeName = String(describing: V.self)
		guard let v =
			UINib(nibName: viewTypeName, bundle: nil).instantiate(withOwner: nil, options: nil).first as? V else { return }
		v.viewController = self
		v.setup()
		v.style()
		self.view = v
	}
}

class AddItemViewController2: IBViewControllerWithLocalState<AddItemView2> {
...
...
}
`
