### ISSUE TITLE
Support for UI test in ViewController containment

### ISSUE THREAD

**Issue by smaramba** [BendingSpoons/tempura-swift#56]
# The problem

The current implementation of UI Tests is centred about `View`s and the injection of `ViewModel`s representing testing conditions for that View.

Let's take an example View to test:

```swift
class ViewToTest: UIView, ViewControllerModellableView {
  let title = UILabel()
  let preview = Preview()
    
  ...
    
  func update(oldModel: ViewToTestViewModel?) {
    // handle the update
  }
}
```

A possible UI Test is written in the form:

```swift
class ViewToTestUITest: XCTestCase, UITestCase {
  typealias V = ViewToTest
    
  let vm1 = ViewToTestViewModel(title: "A test title")
  let vm2 = ViewToTestViewModel(title: "A very very very long test title")
   
  let context = UITests.Context<ViewToTest>()
  
  func test() {
    self.uiTest(testCases: ["first_test": vm1,
                            "second_test": vm2],
               context: context)
    
  }
}
```

Extending the usual `XCTestCase` and conforming to `UITestCase` protocol, we have access to the `uiTest` function that is taking the testCases and the context of the tests in input.
Running the test, for each test case the View will be instantiated and updated with the provided ViewModel.

**If you View is using VC containment this will not work**.

Take for instance the same View but using VC containment for the `preview` part:

```swift
class ViewToTest: UIView, ViewControllerModellableView {
  let title = UILabel()
  /// The VC is responsible to inject a View managed by a different VC inside this ContainerView
  let preview = ContainerView()
  
    
    func update(oldModel: ViewToTestViewModel?) {
      /// handle the update only of the `title` part of the View
      /// the `preview` will receive updates through a different VC
    }
}
```

The ViewController has the responsibility of doing the setup of the contained ViewController:

```swift
class ViewToTestViewController: ViewController<ViewToTest> {
  lazy var previewVC = PreviewViewController(store: self.store)
    
  override func setup() {
    /// link the `preview` to the VC that should manage it
    self.add(self.previewVC, in: self.rootView.preview)
  }
}
```

In this way, the `preview` now is an independent piece of UI not managed by this View (that will only manage the layout), thus when the UI test will set the testing ViewModel, the preview is not affected and **we are not able to test the preview** in this context.

# Proposed Solution

The proposed solution is based on the fact that the ViewController is doing the configuration of all the children ViewControllers. We propose to create a different protocol that will handle the UI test at the ViewController level:

```swift
protocol UIVCTestCase {
  associatedtype VC: AnyViewController
  
  /// perform the UI tests
  func uiTest(testCases: [String], context: UITests.VCContext<VC>)
   
  /// return true if the View is ready for the UI test
  func isViewReady(_ view: VC.V, identifier: String) -> Bool
    
  /// used to provide the VC
  var viewController: VC { get }
    
  /// configure the VC for the specified `testCase`
  /// here you should manually inject the ViewModels for all the children VCs
  func configure(vc: VC, for testCase: String)
}
```

Two things to notice here:

1. the instantiation of the ViewController cannot happen automatically like for the View in the `UITestCase` as, requiring the ViewController to be instantiable with an empty init, means that we add a `required init()`  in the `ViewController` class. This means that each subclass of ViewController in our apps must have an empty init that you need to write each time. This is super cumbersome and we want to avoid that. Hence, in `UIVCTestCase` you are responsible for the initialization of the ViewController returning it as the viewController variable.
2. the injection of the ViewModels is done manually inside the `configure(vc: VC, for testCase: String)` method. An automatic injection like the one we are performing in the `UITestCase` is not possible here, given that ViewModels are of different types and also we don't know the structure of the children ViewControllers.

### Example of UI Test for VC containment

```swift
class ViewToTestVCUITest: XCTestCase, UIVCTestCase {
  
  var viewController: ViewToTestViewController {
    let testStore = Store<AppState, EmptySideEffectDependencyContainer>()
    let vc = ViewToTestViewController(store: testStore)
    vc.shouldConnectWhenVisible = false
    return vc
  }
  
  let vm = ViewToTestViewModel(label: "A test title")
  let previewVM = PreviewViewModel(status: .stopped)
  
  let context = UITests.VCContext<ViewToTestViewController>()
  
  func configure(vc: ViewToTestViewController, for testCase: String) {
    vc.viewModel = vm
    vc.previewVC.viewModel = previewVM
  }
  
  func test() {
    self.uiTest(testCases: ["first_test"],
               context: context)
    
  }
}
```

**Comment by frankdilo** [comment]
I like the proposal. Some ideas for improvements below.

* * *

One thing I would change (probably a typo in your proposal) is to have `isViewControllerReady` instead of `isViewReady` in the `UIVCTestCase` protocol.

* * *

Another thing is that having free strings for the `testCase` argument of `func configure(vc: ViewToTestViewController, for testCase: String) {` means that we will have to define enums and `configure` methods will likely look like this:

```swift
func configure(vc: ViewToTestViewController, for testCase: String) {
  guard let testCase = TestCase(rawValue: testCase) else { fatalError() } 
  switch testCase {
  // ...
  }
}
```

I wonder if we could make the test case generic also for this enum that we will end up writing for sure for any non-trivial test case.

* * *

Last thing is the naming of the types: `UIVCTestCase` and `UITestCase`. I would change them: `UITestCase` (looks like a UIKit class for a newcomer, even if this is outside the scope of this discussion) and `UIVCTestCase` is not really readable. `ViewTestCase` and `ViewControllerTestCase` would be better names imho.

**Comment by smaramba** [comment]
> One thing I would change (probably a typo in your proposal) is to have isViewControllerReady instead of isViewReady in the UIVCTestCase protocol.

UI tests are still about the View, we are waiting for the View to be ready to be rendered, not the ViewController (there is no concept of ViewController ready to be rendered).
You don't have to use info at the ViewController level in order to understand if the View is ready.

> I wonder if we could make the test case generic also for this enum that we will end up writing for sure for any non-trivial test case.

Correct, I'm really torn on this. At the end of the day it's adding a single line:
`guard let testCase = TestCase(rawValue: testCase) else { fatalError() } `
vs requiring an enum that for some tests you don't really need as the test is only about a single screen. I don't have a strong opinion.

> Last thing is the naming of the types: UIVCTestCase and UITestCase. I would change them: UITestCase (looks like a UIKit class for a newcomer, even if this is outside the scope of this discussion) and UIVCTestCase is not really readable. ViewTestCase and ViewControllerTestCase would be better names imho.

I really prefer the naming you are proposing. I will deprecate the old naming and introduce this one.

**Comment by fonesti** [comment]
### Small improvements proposal
I would like to propose a small improvement for multiple test cases.
Currently we should write the name of the test case twice:
- in `test()`
- in a switch on `testCase` inside `configure(vc:for:)`

It would be great to merge `test()` and `configure()` in something like
```swift
  func test() {
    self.uiTest([
      .testCase("first") { vc in
        vc.viewModel = vm
        vc.preview.viewModel = previewVM
      },
      .testCase("second") { vc in
        vc.viewModel = vm_2
        vc.preview.viewModel = previewVM_2
      },
    ],
    context: context)
  }
```

Also an `isReady` function, similar to the one we have in the standard `UITestCase`, would be very handy.

### A more broad consideration
In the example we already have a `testStore` with a `testState`, have we ever consider using just that for test? 
Although we should consider all the drawbacks, it sounds like a very natural and symmetrical extension of the actual testing framework.
A View is typed on its `ViewModel` --> it's tested with variations of its viewModel.
A ViewController is typed on the app's `State` --> it's tested with variations of the app's state.

- We could avoid the type system barrier of managing an unknown hierarchy of ViewModels, and have automatic injection and maybe instantiation.
- `configure()` would be optional and used just to tweak the local state(s).
- Although creating a test `State` can be  longer than creating a test `ViewModel`, once we have one, it can be tweaked to create all the viewModels of different test cases very quickly.
At the moment we have to manually configure a lot of ViewModel with a lot of parameters each.
These parameter are usually difficult/tedious to create/configure one by one just for test while we already have the code that translates the state to each ViewModel in the app.
At a large scale VC-testing might be quicker and more convenient than View-testing even when VC containment is not involved.

**Comment by smaramba** [comment]
> It would be great to merge test() and configure()

In the average use case we will have an enum for the test cases so we will not end up repeating the name of the tests. In general, we should consider if this tweak is improving in readability, in that case, we should favour that. My gut feeling is that it will be slightly less readable as there is more indentation, but let's see in a couple of real cases and decide based on that.

> Also an isReady function, similar to the one we have in the standard UITestCase, would be very handy.

we have that:
```swift
func isViewReady(_ view: VC.V, identifier: String) -> Bool
```
> In the example we already have a testStore with a testState, have we ever consider using just that for test?
Although we should consider all the drawbacks, it sounds like a very natural and symmetrical extension of the current test framework.

We could add another protocol for UI tests based on the entire state. I would not discard ViewModel based testing as in some use cases you will end up writing a lot more code than necessary if you need the entire state for the tests. But sometimes can be a nice addition. I would address this in a separate issue tho.

**Comment by smaramba** [comment]
Implemented.
