### ISSUE TITLE
Problem with Demo

### ISSUE THREAD

**Issue by timglorioso** [BendingSpoons/tempura-swift#59]
In the Demo, I'm noticing some odd behavior that I think is related to Katana initializing the State twice, and I'm not sure how to work around this.

Basically, the initial render is out of sync with the latest state (maybe as a result of [asynchronously calling the state initializer](https://github.com/BendingSpoons/katana-swift/blob/b598ce859337d2b2efb3445da40aab112d5ecdce/Katana/Store.swift#L256)?).

A couple ways you can see this in action:
- tap an item to edit it, the modal's text field is empty
- tap a checkbox, the list re-renders and the item remains un-checked

After an interaction presumably syncs the UI with the latest state, everything works fine (although I also notice the app crashes upon relaunch, possibly unrelated).

Worth noting that since the AppState initializer is called twice, two different sets of items (with different IDs) are produced.

Any advice from using these libraries in production? 😄 Really cool stuff here, just want to make sure I'm using it correctly.

Here's my workspace:
Xcode 10
iOS (simulator) 10 + 12
Swift 4.2
Katana 3.0.0
Tempura 3.0.1

**Comment by smaramba** [comment]
Thanks!
Should be fixed in latest version.
