### ISSUE TITLE
[Proposal] Remove returned promise from VC's dispatch

### ISSUE THREAD

**Issue by bolismauro** [BendingSpoons/tempura-swift#72]
### Main Proposal
The Katana and Tempura architecture promote the implementation of the business logic using `Side Effect` and `State Updater`. Because of this, we really don't want to write business logic in VCs if it is not necessary (e.g., UIKit-related) logic.

We noticed that having the `dispatch` function returning a `Promise` leads in the opposite direction. In fact, it is quite easy to write a piece of logic that is half in the Katana world and half in the VC

```swift
// in a vc
func onTap() {
 self.store.dispatch(UpdateStore()).then {
   self.localState.updateDone = true
 }
}
```

This may cause trouble, confusion and hard-to-debug situations.

We feel that we can do much better than this and promote a better logic definition. In particular, the proposal would be to remove the returned `Promise` from the VC's dispatch to discourage this kind of half-here-and-half-there situation.

### But, ...
During our discussing we haven't managed to establish with absolute certainty that this removal won't create situations where the alternative is worse. Because of this, we suggest introducing an `unsafe_dispatch` method that returns the `Promise` value. In this way, we could leverage this `unsafe` API when it is necessary. We feel that the naming of this API should discourage a massive usage and could help automatic tools (e.g., Swiftlint) catching usages in an easier way.

### Breaking
This change is breaking by design, and there is no way around that

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199108774605801/1199216785267265) by [Unito](https://www.unito.io/learn-more)

**Comment by FEC-bendingspoons** [comment]
This is being explored for the next version of Tempura. Currently, you can try out v5.0.4-beta that has the implementation of this proposal.

The actual implementation is contained [here](https://github.com/BendingSpoons/tempura-swift/pull/75).

**Comment by LorDisturbia** [comment]
Already implemented in Tempura 5
