### ISSUE TITLE
Hooks are not working in ViewControllerTestCase

### ISSUE THREAD

**Issue by danyf90** [BendingSpoons/tempura-swift#81]
### Current Implementation
The UITests hooks are based on the `HookableViewController` class that is used to present the view in the `ViewTestCase`.

### Problem
The `ViewControllerTestCase` use the VC provided by the test case instead of the `HookableViewController`, and hence hooks are not working

### Possible Solution
After a quick look it seems there isn't an easy way to do this.
If we don't find one, we should at least remove the hooks from the interface of the `ViewControllerTestCase`

**Comment by smaramba** [comment]
Fixed, we removed the hooks.
